---
functional:
  - требование 9
  - требование 8
  - требование 3
  - требование 4
non-functional:
  - требование 2
  - требование 1
  - требование 6
  - требование 7
  - требование 10
  - требование 5
implicit:
  - после добавления товара в корзину, пользователь может продолжить выбор товаров в каталоге
  - корзина должна хранится в сессии браузера
  
  
